import { ICountry } from "../../../core/interfaces/ICountry";

export const countries: ICountry[] = [
  { name: "Ghana", code: "GH", currency: "GHS", phone_code: "+233", symbol: "₵", flag: "🇬🇭", },
  { name: "United States", code: "US", currency: "USD", phone_code: "+1", symbol: "", flag: "🇺🇸", },
  { name: "United Kingdom", code: "GB", currency: "GBP", phone_code: "+44", symbol: "£", flag: "🇬🇧", },
  { name: "Angola", code: "AO", currency: "AOA", phone_code: "+244", symbol: "Kz", flag: "🇦🇴", },
  { name: "Benin", code: "BJ", currency: "CDF", phone_code: "+229", symbol: "Fr", flag: "🇧🇯", },
  { name: "Burkina Faso", code: "BF", currency: "CDF", phone_code: "+226", symbol: "Fr", flag: "🇧🇫", },
  { name: "Brazil", code: "BR", currency: "BRL", phone_code: "+55", symbol: "R", flag: "🇧🇷", },
  { name: "Canada", code: "CA", currency: "CAD", phone_code: "+1", symbol: "", flag: "🇨🇦", },
  { name: "Democratic Republic of the Congo", code: "CD", currency: "CDF", phone_code: "+243", symbol: "Fr", flag: "🇨🇩", },
  { name: "Cameroon", code: "CM", currency: "CDF", phone_code: "+237", symbol: "Fr", flag: "🇨🇲", },
  { name: "Ivory Coast", code: "CI", currency: "XOF", phone_code: "+225", symbol: "CFA", flag: "🇨🇮", },
  { name: "China", code: "CN", currency: "CNY", phone_code: "+86", symbol: "¥", flag: "🇨🇳", },
  { name: "Egypt", code: "EG", currency: "EGP", phone_code: "+20", symbol: "E£", flag: "🇪🇬", },
  { name: "Ethiopia", code: "ET", currency: "ETB", phone_code: "+251", symbol: "Br", flag: "🇪🇹", },
  { name: "France", code: "FR", currency: "EUR", phone_code: "+33", symbol: "€", flag: "🇫🇷", },
  { name: "Gabon", code: "GA", currency: "GAB", phone_code: "+241", symbol: "Fr", flag: "🇬🇦", },
  { name: "Gambia", code: "GM", currency: "GMD", phone_code: "+220", symbol: "D", flag: "🇬🇲", },
  { name: "Equatorial Guinea", code: "GQ", currency: "GQE", phone_code: "+240", symbol: "Fr", flag: "🇬🇶", },
  { name: "South Africa", code: "ZA", currency: "ZAR", phone_code: "+27", symbol: "R", flag: "🇿🇦", },
  { name: "India", code: "IN", currency: "INR", phone_code: "+91", symbol: "₹", flag: "🇮🇳", },
  { name: "Kenya", code: "KE", currency: "KES", phone_code: "+254", symbol: "KSh", flag: "🇰🇪", },
  { name: "Liberia", code: "LR", currency: "LRD", phone_code: "+231", symbol: "", flag: "🇱🇷", },
  { name: "Morocco", code: "MA", currency: "MAD", phone_code: "+212", symbol: "Dh", flag: "🇲🇦", },
  { name: "Mali", code: "ML", currency: "CDF", phone_code: "+223", symbol: "Fr", flag: "🇲🇱", },
  { name: "Mauritius", code: "MU", currency: "MUR", phone_code: "+230", symbol: "Rs", flag: "🇲🇺", },
  { name: "Malawi", code: "MW", currency: "MWK", phone_code: "+265", symbol: "MK", flag: "🇲🇼", },
  { name: "Niger", code: "NE", currency: "NGN", phone_code: "+227", symbol: "₦", flag: "🇳🇪", },
  { name: "Nigeria", code: "NG", currency: "NGN", phone_code: "+234", symbol: "₦", flag: "🇳🇬", },
  { name: "Réunion", code: "RE", currency: "EUR", phone_code: "+262", symbol: "€", flag: "🇷🇪", },
  { name: "Rwanda", code: "RW", currency: "RWF", phone_code: "+250", symbol: "RF", flag: "🇷🇼", },
  { name: "Sudan", code: "SD", currency: "SDG", phone_code: "+249", symbol: "S£", flag: "🇸🇩", },
  { name: "South Sudan", code: "SS", currency: "SSP", phone_code: "+211", symbol: "£", flag: "🇸🇸", },
  { name: "Senegal", code: "SN", currency: "XOF", phone_code: "+221", symbol: "CFA", flag: "🇸🇳", },
  { name: "Sierra Leone", code: "SL", currency: "SLL", phone_code: "+232", symbol: "Le", flag: "🇸🇱", },
  { name: "Eswatini", code: "SZ", currency: "SZL", phone_code: "+268", symbol: "E", flag: "🇸🇿", },
  { name: "Togo", code: "TG", currency: "XOF", phone_code: "+228", symbol: "CFA", flag: "🇹🇬", },
  { name: "Tanzania", code: "TZ", currency: "TZS", phone_code: "+255", symbol: "Sh", flag: "🇹🇿", },
  { name: "Uganda", code: "UG", currency: "UGX", phone_code: "+256", symbol: "USh", flag: "🇺🇬", },
  { name: "Zambia", code: "ZM", currency: "ZMW", phone_code: "+260", symbol: "K", flag: "🇿🇲", },
  { name: "Zimbabwe", code: "ZW", currency: "ZWD", phone_code: "+263", symbol: "Z$", flag: "🇿🇼", },
];
